# Generated by Django 5.2.6 on 2025-09-13 05:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('school_student', 'School Student'), ('college_student', 'College Student'), ('passout', 'Graduate/Passout')], max_length=20)),
                ('level', models.CharField(blank=True, choices=[('class_10', 'Class 10'), ('class_11', 'Class 11'), ('class_12', 'Class 12')], max_length=20, null=True)),
                ('year', models.CharField(blank=True, choices=[('first_year', '1st Year'), ('second_year', '2nd Year'), ('third_year', '3rd Year'), ('fourth_year', '4th Year')], max_length=20, null=True)),
                ('field', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('medical', 'Medical'), ('business', 'Business/Commerce'), ('arts', 'Arts/Humanities'), ('science', 'Science')], max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('concerns', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'user_sessions',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.usersession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='chat_messag_session_4a3fea_idx')],
            },
        ),
    ]
