# Generated by Django 5.2.6 on 2025-09-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usersession_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='roadmap_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
